Fix request insert
dpindur/get-good pull request #1
Opened 2018-08-17 06:27 UTC by dzflack

- Fix minor formatting and add files to gitignore.
- Add *UNIQUE* constraint to URI column.
- Insert initial request URIs into database using a transaction.

2018-08-17 07:10 UTC, dpindur commented on libgetgood/updater.go
> +			log.Printf("URLs Added to database\n")
I think we can drop these two log statements as they were mainly for debugging the issue.

If we want to include them later I think we should put them in the addURLs function as it's called elsewhere as well.

2018-08-17 07:11 UTC, dpindur commented on libgetgood/database.go
> +		log.Printf("Failed to begin transaction")
We can drop this as the error bubbles up and is printed elsewhere

2018-08-17 07:15 UTC, dpindur requested changes
Looks great! Just got to clean up some logging and then we're all good to go! 👌

2018-08-18 13:11 UTC, dzflack commented
Requested changes made in d729cae7a8507055796c36101eaa2e946debd2b1.

2018-08-19 04:51 UTC, dpindur approved these changes

2018-08-19 04:51 UTC, merged